server:
  port: 9090
spring:
  rabbitmq:
    host: 192.168.56.132
    virtual-host: /
    port: 5672
    publisher-confirm-type: correlated
    publisher-returns: true

  redis:
    host: 192.168.56.132
    port: 6379

  datasource:
    username: root
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/book?characterEncoding=utf-8&useSSL=false

mybatis:
  mapper-locations: classpath:/mapper/*
